version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "voltbras"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "volt"
      # You can use whatever password you like
      MYSQL_PASSWORD: "12345678*"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "12345678*"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  apollo:
    build: .
    command: npm run devStart
    volumes:
      - /usr/app/
    ports:
      - "4000:4000"
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 2
      WAIT_SLEEP_INTERVAL: 4
      WAIT_HOST_CONNECT_TIMEOUT: 6
      DATABASE: voltbras
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: volt
      DATABASE_PASSWORD: 12345678*
    depends_on: 
      - db

# Names our volume
volumes:
  my-db:
