version: '3.3'
services:
  apollo:
    image: node
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "4000:4000"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'voltbras'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'volt'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345678*'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345678*'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: